<?php

namespace BadgeBox\BadgeBoxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Challenge_usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeUsersRepository extends EntityRepository
{
}
